PUT http://localhost:3000/student
Content-Type: application/json

{
  "name": "a",
  "email": "",
  "birthDate": "1900-01-01",
  "id_class": "1"
}

###
PUT http://localhost:3000/teacher
Content-Type: application/json

{
  "name": "Novo professor",
  "email": "professor@gmail.com",
  "birthDate": "1900-01-01"
}

###
PUT http://localhost:3000/class
Content-Type: application/json

{
  "name": "novaTurma",
  "startdate": "2022-01-01",
  "enddate": "2022-12-31",
  "module": "3",
  "id_teacher": "99"
}